### ISSUE TITLE
[Bug] Equipment and Quick Slots compatibility issue with upgrading

### ISSUE THREAD

**Issue by Jcdutt** [blaxxun-boop/Backpacks#15]
It seems that trying to upgrade the backpack with Equipment and Quick Slots by RandyKnapp installed doesn't add any extra space.

![Level3](https://github.com/blaxxun-boop/Backpacks/assets/5200800/bfd48d1f-fcda-422f-a519-a6d36e5c51fb)
![Level3NoEQS](https://github.com/blaxxun-boop/Backpacks/assets/5200800/a0830012-e3dd-4583-bccc-fa6c07ef719c)

**Comment by blaxxun-boop** [comment]
Equipment and quick slots is the worst implementation of that feature and barely works with any other inventory mod, due to it's very weird implementation. It's also buggy as hell and will even occasionally delete your items if you die.

Just use any of the alternatives. They work waaay better.
https://valheim.thunderstore.io/package/Azumatt/AzuExtendedPlayerInventory/

Just dump all your stuff into a chest, before switching. And don't forget to enable the features you want in the config file.
